### ISSUE TITLE
Reproducible Code Base

### ISSUE THREAD

**Issue by MayunaGupta** [IVRL/Tempsal#1]
Hi team,

We are highly interested in your work and would love to reproduce it on our dataset. Can you provide an estimate on when the code will be uploaded

Regards
Mayuna

**Comment by baharay** [comment]
Hi Mayuna,

Thank you for your interest. We provided a notebook for inference with better instructions now. Please let us know if you have any problems.

Best,
Bahar

**Comment by derenrich** [comment]
The instructions say to use the requirements.txt file. But that was never checked in?

**Comment by baharay** [comment]
requirements.txt file is under the src/ folder.
